### ISSUE TITLE
Simple push from workflow

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/byte-level-care#99]
```yaml
  test:
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -- files
        git commit -m "update"
        git push
```
